kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-to-tunnel
spec:
  podSelector:
    matchLabels:
      {{- include "alpine.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
    - from:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            allow-to-tunnel: "true"
