apiVersion: v1
kind: Service
metadata:
  name: {{ include "alpine.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.service.ports.rpc }}
    - name: p2p
      port: {{ .Values.service.ports.p2p }}
    - name: zmqpubrawtx
      port: {{ .Values.service.ports.zmqpubrawtx }}
    - name: zmqpubrawblock
      port: {{ .Values.service.ports.zmqpubrawblock }}
    - name: trpc
      port: {{ .Values.service.ports.trpc }}
    - name: tp2p
      port: {{ .Values.service.ports.tp2p }}
    - name: tzmqpubrawtx
      port: {{ .Values.service.ports.tzmqpubrawtx }}
    - name: tzmqpubrawblock
      port: {{ .Values.service.ports.tzmqpubrawblock }}
  selector:
    {{- include "alpine.selectorLabels" . | nindent 4 }}
